### ISSUE TITLE
Interval distance doesnt change on Garmin

### ISSUE THREAD

**Issue by muzzthegreat** [PeterK-end/swim-data-analyser#27]
Hi there,
Just started using the app, mostly because Garmin's auto lap is so sensitive that it creates laps when you are resting, if you move your watch too much.

I've successfully combined 2 laps in using the laps to change the interval from 225m to 200m, exported it FIT file and reimported it into Garmin Connect. Garmin picks up the total metres of my swim correctly, the total laps of the interval correctly (8 laps x 25m =200m), but the sum of the laps in that interval still shows 225m.
Is there anything that can be done to correct this?

Happy to share more info if needed.
Thanks 
![Image](https://github.com/user-attachments/assets/1af166ab-a8ec-4e62-a5bf-ba240ab1e223)

**Comment by alexbrett** [comment]
Hi @PeterK-end, I've just reproduced this myself - had a few intervals to fix up on a long swim where each was 1k - having done so (on v0.6.0-16-g3c6a37e) it all seemed OK, but upon importing the FIT into Strava whilst it shows the right overall distance, the laps where I merged are still showing up as their original distances:
<img width="1042" height="666" alt="Image" src="https://github.com/user-attachments/assets/bb3199e0-c077-4f93-b6d8-568dfb2130be" />

I've attached the original and modified FITs in a zip file.

[fits.zip](https://github.com/user-attachments/files/23434955/fits.zip)

**Comment by PeterK-end** [comment]
I am on it. Thanks for sharing @alexbrett. I introduced this as a side effect of renumbering length indices after edit operations. I think I was now able to fix it here 3215566ce160a7214a77c018587bcfa2816ad061 but I still need to do some testing. I will report back next week.

**Comment by PeterK-end** [comment]
Hi I addressed the issue in 3215566ce160a7214a77c018587bcfa2816ad061, it is deployed in the latest version (v.0.8.0 ([86c7f3f](https://github.com/PeterK-end/swim-data-analyser/commit/86c7f3f)) and should now be fixed. I tested it with your workout @alexbrett. Please let me know wheter it also works for you @alexbrett, @muzzthegreat.

**Comment by muzzthegreat** [comment]
Hi There,
Unfortunately it still isnt working. Attached is the data from swimdata. The first 8 laps didnt detect correctly on my watch and only picked up 75m. I merged them and then split them into 8 laps (200m). It correctly changed from a total of 2075m to 2200m, but when I upload to garmin and strava, they have the correct total distance (2200m), but still show the first lap as 75m.

![Image](https://github.com/user-attachments/assets/a0e3d01a-46e1-4fda-9cbf-1a495ed742a0)
![Image](https://github.com/user-attachments/assets/36595b21-03c8-473c-8519-e7cf893f3450)
![Image](https://github.com/user-attachments/assets/7e6d1211-dcf1-40a7-8459-5961fbe1ce9d)

**Comment by PeterK-end** [comment]
This is weird, if I do the edits it seems to work with Garmin Connect: 

<img width="2492" height="1226" alt="Image" src="https://github.com/user-attachments/assets/16c05458-30d3-4d31-a501-058c179f9077" />
 
Have you tried Garmin Connect or is Strava the main problem?
